### ISSUE TITLE
KeePassRFID 2.0.1 -- This plugin is incompatible with the current KeePass version

### ISSUE THREAD

**Issue by tps800** [leosac/keepassrfid#7]
Upgrading KeePassRFID to 2.0.1 KeePass2 2.50 reports "The following plugin is incompatible with the current KeePass version: 'C:\Program Files\KeePass2\Plugins\KeePassRFID.dll'"
Same for KeePassRFID.plgx

**Comment by Maxhy** [comment]
Can you check the detailed error following this message @tps800?
May it be related to #6?

**Comment by YoNevelt** [comment]
It is definitely the same. It started the same way :)

**Comment by Maxhy** [comment]
Closing is as duplicate then. Feel free to comment otherwise.
